# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b52a81b4e92437e346f4b7c1fa7e408fa17d4cb794a9d6078a891c1c8586616c3d44730abb7b25e18bab9a2da6d40555a380f0126789ed38cb296f2f2cfb423

test:
  secret_key_base: 6d2726e52f9134b9c22ad4d4c427cea810064b21471e021769beb3fbb3a67d841e0d6437a368824ce1057d6363114bfe6e8a114591bd55843365f03a99401031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
